apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  annotations:
  name: letsencrypt-prod
  namespace: monitoring
spec:
  acme:
    email: luca.barze@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
