apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: meme-backend
  namespace: meme
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meme-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: application_it_local_backend_MemeRequestService_createdMeme_total
      targetAverageValue: 3
